config/routes.rb
Rails.application.routes.draw do
  #Static Pages
  root 'static_pages#home'
  get 'upgrade', to: 'static_pages#upgrade'


  resources :galleries

  resources :projects do
    resources :comments, only: [:create, :destroy] do
      collection do
        get 'new/(:parent_id)', to: 'comments#new', as: 'new'
      end
    end
    member do
      post 'like'
      delete 'unlike'
    end
  end
  get 'projects/:id/comments/:comment_id', to: 'projects#show', as: 'project_comment_show'

  get 'profile/:id', to: 'profiles#show', as: 'profile'

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             },
             skip: [:registrations, :sessions]


  get 'signin', to: 'static_pages#home', as: 'new_user_session'



  devise_scope :user do
    namespace 'users', as: 'user' do
      get 'check_username', to: 'registrations#check_username'
      get 'check_email', to: 'registrations#check_email'
      get 'check_password', to: 'registrations#check_password'
      post 'preregistration', to: 'registrations#preregistration'
    end
    namespace 'users', as: 'user_registration' do
      post '', to: 'registrations#create'
      get 'edit', to: 'registrations#edit'
      patch '', to: 'registrations#update'
      put '', to: 'registrations#update'
      delete '', to: 'registrations#destroy'
    end
    namespace 'users', as: '' do
      post 'switch_user', to: 'sessions#switch_user', as: 'user_switch_user'
      post 'sign_in', to: 'sessions#create', as: 'user_session'
      delete 'sign_out', to: 'sessions#destroy', as: 'destroy_user_session'
    end
  end

  #Announcement reading
  mount Starburst::Engine => '/starburst'

  #Routes to showcase solid layout
  namespace 'solid' do
    get 'index', to: 'solid#index'
    get 'about', to: 'solid#about'
    get 'contact', to: 'solid#contact'
    get 'blog', to: 'solid#blog'
    get 'portfolio', to: 'solid#portfolio'
    get 'single-post', to: 'solid#single_post'
    get 'single-project', to: 'solid#single_project'
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :galleries

  #Project Likes
  has_many :project_likes, dependent: :destroy
  has_many :liking_users, through: :project_likes, source: :user
  alias_attribute :likes, :project_likes_count

  #Project Tags
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates_presence_of :title
  validates_length_of :title, minimum: 5
  validates_presence_of :thumbnail
  validates_presence_of :author


  def root_comments
    comments.root_comments
  end

  def add_like(current_user)
    if liking_users.include? current_user
      false
    else
      liking_users << current_user
      true
    end
  end

  def remove_like(current_user)
    if liking_users.include? current_user
      liking_users.delete current_user
      true
    else
      false
    end
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).projects
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #Verify that every action is 'authorized', otherwise throw an exception
  check_authorization
  #Will automatically do the equivalent of 'set project' for us
  load_resource
  #Will perform 'authorize! action_name, @project' for all the basic actions
  #We can manually call authorize! in any non-RESTful actions we make, using one of the restful actions as its check
  authorize_resource only: Ability::RESTFUL_ACTIONS


  respond_to :html, :json

  def index
    if params[:tag]
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.all
    end
    @projects = @projects.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def create
    @project = Project.new(project_params)

    @project.author= current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

  def like
    authorize! :create, ProjectLike
    result = @project.add_like(current_user)
    respond_to do |format|
      format.html do
        redirect_to project_path(@project)
      end
    end
  end

  def unlike
    authorize! :destroy, ProjectLike
    result = @project.remove_like(current_user)
    respond_to do |format|
      format.html do
        redirect_to project_path(@project)
      end
    end
  end

  def show
    @liked = current_user && @project.liking_users.include?(current_user)

    @all_comments = @project.comments.includes(:author)
    if params[:comment_id]
      @root_comments = [@project.comments.find(params[:comment_id])]
    end
  end

  def edit
  end

  def update
    flash[:notice] = "#{@project.title} was successfully updated." if @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    flash[:notice] = "#{@project.title} was successfully destroyed."
    respond_with @project
  end

  private

  def project_params
    params.require(:project).permit(:title, :instructions, :about, :thumbnail, :all_tags)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def heart_link
    if can? :create, ProjectLike
      if @liked
        link_to unlike_project_path(@project), method: :delete do
          '<i class="fa fa-heart text-danger"></i>'.html_safe
        end
      else
        link_to like_project_path(@project), method: :post do
          '<i class="fa fa-heart-o pull-right"></i>'.html_safe
        end
      end
    else
      '<i class="fa fa-heart-o pull-right"></i>'.html_safe
    end
  end

  def comment_return_link
    if request.path != project_path(@project)
      link_to('View all comments', project_path(@project))
    end
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    max = (max && max.count) || 1
    max = [1, max].max
    tags.take(10).each do |tag|
      index = tag.count.to_f / max * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end

  def id_string_for_user
    id = (current_user.super_admin?) ? 'superuser' : current_user.id
    "data-current-user-id=\"#{id}\"".html_safe
  end

end

app/views/projects/_comment.html.erb
<div class="comment" <%= "data-owner-id=\"#{comment.author.id}\"".html_safe %>>
  <% if comment.deleted %>
      <div>
        <i> Deleted </i>
      </div>
      <div>Deleted Comment</div>
  <% else %>
      <div>
        <strong><i><%= comment.author.username %></i></strong>
      </div>
      <div><%= comment.text %></div>
      <div>
        <%= link_to 'Permalink', project_comment_path(comment.project, comment), class: 'btn btn-xs btn-default' %>
        <%= link_to 'Reply', new_project_comments_path(comment.project, comment), class: 'btn btn-xs btn-default show-logged-in hidden' %>
        <%= link_to 'Delete', project_comment_path(comment.project, comment), class: 'btn btn-xs btn-danger show-for-owner hidden', method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
  <% end %>
  <% next_comments = comment.children_within_array(all_comments) %>
  <% if next_comments.any? %>
      <div>
        <%= render partial: 'comment', collection: next_comments, locals: {all_comments: all_comments} %>
      </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :about %><br>
      <%= f.text_area :about %>
    </div>

    <div class="field">
      <%= f.label :all_tags %><br>
      <%= f.text_area :all_tags %>
    </div>

    <div class="field">
      <%= f.label :instructions %><br>
      <%= f.text_area :instructions %>
    </div>

    <div class="field">
      <%= f.label :thumbnail %><br>
      <%= f.text_field :thumbnail %>
    </div>
    <br/><br/>

    <div class="actions">
      <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit this project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project, class: 'btn btn-info btn-sm' %>
<%= link_to 'Back', projects_path, class: 'btn btn-default btn-sm' %>

app/views/projects/index.html.erb
<h1>List of Projects</h1>
<%= link_to 'New Project', new_project_path, class: 'btn btn-success btn-sm' if can? :create, Project %>
<br/>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= link_to 'Show', project, class: 'btn btn-info btn-sm' %></td>
        <% if can? :edit, project %>
            <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning btn-sm' %></td>
        <% end %>
        <% if can? :destroy, project %>
            <td><%= link_to 'Destroy', project, class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<div class="tags-cloud glassy-bg">
  <h4>Popular Tags</h4>
  <% tag_cloud Tag.counts, %w{tag-cloud1 tag-cloud2 tag-cloud3 tag-cloud4} do |tag, css_class| %>
      <%= link_to tag.name, projects_path(tag: tag.name), class: css_class %>
  <% end %>
</div>
<br>

<div><%= will_paginate @projects %></div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% provide :title, @project.title %>

<!-- *****************************************************************************************************************
 BLUE WRAP
 ***************************************************************************************************************** -->
<div id="blue">
  <div class="container">
    <div class="row">
      <h3><%= @project.title %></h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /blue -->

<!-- *****************************************************************************************************************
 TITLE & CONTENT
 ***************************************************************************************************************** -->

<div class="container mt">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-1 col-md-7 centered">
      <%= image_tag @project.thumbnail, class: 'img-responsive' %>
    </div>

    <div class="col-lg-4 col-md-5">
      <div class="row spacing-sm">
        <div class="col-lg-12">
          <h4>Instructions</h4>

          <div class="hline"></div>
          <p class="instructions">
            <%= @project.instructions %>
          </p>
        </div>
        <div class="col-lg-12">
          <div class="spacing"></div>
          <h4>Project Details
            <span class="pull-right">
              <%= @project.likes %>
              <%= heart_link %>
            </span>
          </h4>

          <div class="hline"></div>
          <p><b>Created:</b> <%= @project.created_at %></p>

          <p><b>Last Modified:</b> <%= @project.updated_at %></p>

          <p><b>Author:</b> <%= link_to @project.author.username, profile_path(@project.author) %></p>

          <p><b>Tags:</b>
            <% @project.tags.pluck(:name).each do |x| %>
                <%= link_to x, projects_path(tag: x), class: 'btn btn-xs btn-theme' %>
            <% end %>
          </p>

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="spacing"></div>
      <h3><%= @project.title %></h3>

      <div class="hline"></div>
      <p>
        <%= @project.about %>
      </p>
      <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning' if can? :edit, @project %>
      <%= link_to 'Destroy', @project, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} if can? :destroy, @project %>

      <div id="comments" <%= id_string_for_user if current_user %>>
        <h3>Comments</h3>

        <%= comment_return_link %>

        <% cache([@project, 'comments']) do %>
            <% @root_comments ||= @all_comments.root_comments %>
            <% if @root_comments.any? %>
                <div>
                  <%= render partial: 'comment', collection: @root_comments, locals: {all_comments: @all_comments} %>
                </div>
            <% else %>
                <em>No comments yet</em><br/>
            <% end %>
        <% end %>
        <br/>
        <%= link_to 'Leave a comment', new_project_comments_path(@project), class: 'btn btn-primary btn-m' if can? :create, Comment %>

      </div>
    </div>

  </div>
  <!-- /row -->
</div>
<!-- /container -->