config/routes.rb
Rails.application.routes.draw do
  #Static Pages
  root 'static_pages#home'
  get 'upgrade', to: 'static_pages#upgrade'


  resources :galleries

  resources :projects do
    resources :comments, only: [:create, :destroy] do
      collection do
        get 'new/(:parent_id)', to: 'comments#new', as: 'new'
      end
    end
    member do
      post 'like'
      delete 'unlike'
    end
  end
  get 'projects/:id/comments/:comment_id', to: 'projects#show', as: 'project_comment_show'

  get 'profile/:id', to: 'profiles#show', as: 'profile'

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             },
             skip: [:registrations, :sessions]


  get 'signin', to: 'static_pages#home', as: 'new_user_session'



  devise_scope :user do
    namespace 'users', as: 'user' do
      get 'check_username', to: 'registrations#check_username'
      get 'check_email', to: 'registrations#check_email'
      get 'check_password', to: 'registrations#check_password'
      post 'preregistration', to: 'registrations#preregistration'
    end
    namespace 'users', as: 'user_registration' do
      post '', to: 'registrations#create'
      get 'edit', to: 'registrations#edit'
      patch '', to: 'registrations#update'
      put '', to: 'registrations#update'
      delete '', to: 'registrations#destroy'
    end
    namespace 'users', as: '' do
      post 'switch_user', to: 'sessions#switch_user', as: 'user_switch_user'
      post 'sign_in', to: 'sessions#create', as: 'user_session'
      delete 'sign_out', to: 'sessions#destroy', as: 'destroy_user_session'
    end
  end

  #Announcement reading
  mount Starburst::Engine => '/starburst'

  #Routes to showcase solid layout
  namespace 'solid' do
    get 'index', to: 'solid#index'
    get 'about', to: 'solid#about'
    get 'contact', to: 'solid#contact'
    get 'blog', to: 'solid#blog'
    get 'portfolio', to: 'solid#portfolio'
    get 'single-post', to: 'solid#single_post'
    get 'single-project', to: 'solid#single_project'
  end

end

app/controllers/solid/solid_controller.rb
class Solid::SolidController < ApplicationController

  def index
    flash[:notice] = 'helloworld'
    js :portfolio
  end

  def about
  end

  def contact
  end

  def blog
  end

  def portfolio
  end

  def single_post
  end

  def single_project
    js :portfolio
  end

end

app/views/solid/solid/_extended_footer.html.erb
<!-- *****************************************************************************************************************
 TESTIMONIALS
 ***************************************************************************************************************** -->
<div id="twrap">
  <div class="container centered">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <i class="fa fa-comment-o"></i>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
          industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
          electronic typesetting, remaining essentially unchanged.</p>
        <h4><br/>Marcel Newman</h4>

        <p>WEB DESIGNER - BLACKTIE.CO</p>
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /twrap -->

<!-- *****************************************************************************************************************
 OUR CLIENTS
 ***************************************************************************************************************** -->
<div id="cwrap">
  <div class="container">
    <div class="row centered">
      <h3>OUR CLIENTS</h3>

      <div class="col-lg-3 col-md-3 col-sm-3">
        <img src="img/clients/client01.png" class="img-responsive">
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <img src="img/clients/client02.png" class="img-responsive">
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <img src="img/clients/client03.png" class="img-responsive">
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <img src="img/clients/client04.png" class="img-responsive">
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /cwrap -->

app/views/solid/solid/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SOLID.', solid_index_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <%= nav_link 'HOME', solid_index_path %>
        <%= nav_link 'ABOUT', solid_about_path %>
        <%= nav_link 'CONTACT', solid_contact_path %>
        <%= nav_dropdown 'PAGES ' do %>
            <%= nav_link('BLOG', solid_blog_path) %>
            <%= nav_link('SINGLE POST', solid_single_post_path) %>
            <%= nav_link('PORTFOLIO', solid_portfolio_path) %>
            <%= nav_link('SINGLE PROJECT', solid_single_project_path) %>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>

app/views/solid/solid/about.html.erb
<% provide :title, 'SOLID - Bootstrap 3 Theme' %>

<!-- *****************************************************************************************************************
 BLUE WRAP
 ***************************************************************************************************************** -->
<div id="blue">
  <div class="container">
    <div class="row">
      <h3>About.</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /blue -->


<!-- *****************************************************************************************************************
 AGENCY ABOUT
 ***************************************************************************************************************** -->

<div class="container mtb">
  <div class="row">
    <div class="col-lg-6">
      <img class="img-responsive" src="img/agency.jpg" alt="">
    </div>

    <div class="col-lg-6">
      <h4>More About Our Agency.</h4>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. </p>

      <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
        recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

      <p>Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure
        Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical
        literature, discovered the undoubtable source.</p>

      <p><br/><a href="contact.html" class="btn btn-theme">Contact Us</a></p>
    </div>
  </div>
  <!-- /row -->
</div><!-- /container -->

<!-- *****************************************************************************************************************
 TEEAM MEMBERS
 ***************************************************************************************************************** -->

<div class="container mtb">
  <div class="row centered">
    <h3 class="mb">MEET OUR TEAM</h3>

    <div class="col-lg-3 col-md-3 col-sm-3">
      <%= solid_mouseover_image('Contact Me:',
                                '/solid/img/team/team01.jpg') do %>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
      <% end %>
      <h4>Mark Webber</h4>
      <h5 class="ctitle">CEO</h5>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>

      <div class="hline"></div>
    </div>
    <!-- /col-lg-3 -->

    <div class="col-lg-3 col-md-3 col-sm-3">
      <%= solid_mouseover_image('Contact Me:',
                                '/solid/img/team/team02.jpg') do %>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
      <% end %>
      <h4>Paul Jameson</h4>
      <h5 class="ctitle">LEAD DESIGNER</h5>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>

      <div class="hline"></div>
    </div>
    <!-- /col-lg-3 -->

    <div class="col-lg-3 col-md-3 col-sm-3">
      <%= solid_mouseover_image('Contact Me:',
                                '/solid/img/team/team03.jpg') do %>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
      <% end %>
      <h4>Laura Sommers</h4>
      <h5 class="ctitle">LEAD DEVELOPER</h5>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>

      <div class="hline"></div>
    </div>
    <!-- /col-lg-3 -->

    <div class="col-lg-3 col-md-3 col-sm-3">
      <%= solid_mouseover_image('Contact Me:',
                                '/solid/img/team/team04.jpg') do %>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
          <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
      <% end %>
      <h4>Martin Blunt</h4>
      <h5 class="ctitle">MARKETING</h5>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>

      <div class="hline"></div>
    </div>
    <!-- /col-lg-3 -->

  </div>
  <!-- /row -->
</div><!-- /container -->

<%= render 'extended_footer' %>

app/views/solid/solid/blog.html.erb
<% provide :title, 'SOLID - Bootstrap 3 Theme' %>

<!-- *****************************************************************************************************************
 BLUE WRAP
 ***************************************************************************************************************** -->
<div id="blue">
  <div class="container">
    <div class="row">
      <h3>Blog List.</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /blue -->


<!-- *****************************************************************************************************************
 BLOG CONTENT
 ***************************************************************************************************************** -->

<div class="container mtb">
  <div class="row">

    <!--  BLOG POSTS LIST -->
    <div class="col-lg-8">
      <!--  Blog Post 1 -->
      <p><img class="img-responsive" src="img/post01.jpg"></p>
      <a href="single-post.html"><h3 class="ctitle">Time to change your apps.</h3></a>

      <p>
        <csmall>Posted: April 25, 2014.</csmall>
        |
        <csmall2>By: Admin - 3 Comments</csmall2>
      </p>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book.</p>

      <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
        unchanged.</p>

      <p><a href="single-post.html">[Read More]</a></p>

      <div class="hline"></div>

      <div class="spacing"></div>

      <!--  Blog Post 2 -->
      <p><img class="img-responsive" src="img/post02.jpg"></p>
      <a href="single-post.html"><h3 class="ctitle">Our new project is here.</h3></a>

      <p>
        <csmall>Posted: April 25, 2014.</csmall>
        |
        <csmall2>By: Admin - 3 Comments</csmall2>
      </p>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book.</p>

      <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
        unchanged.</p>

      <p><a href="single-post.html">[Read More]</a></p>

      <div class="hline"></div>

      <div class="spacing"></div>

      <!--  Blog Post 3 -->
      <p><img class="img-responsive" src="img/post03.jpg"></p>
      <a href="single-post.html"><h3 class="ctitle">Logo design contest starts now.</h3></a>

      <p>
        <csmall>Posted: April 25, 2014.</csmall>
        |
        <csmall2>By: Admin - 3 Comments</csmall2>
      </p>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book.</p>

      <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
        unchanged.</p>

      <p><a href="single-post.html">[Read More]</a></p>

      <div class="hline"></div>

    </div>
    <!-- /col-lg-8 -->


    <!--  SIDEBAR -->
    <div class="col-lg-4">
      <h4>Search</h4>

      <div class="hline"></div>
      <p>
        <br/>
        <input type="text" class="form-control" placeholder="Search something">
      </p>

      <div class="spacing"></div>

      <h4>Categories</h4>

      <div class="hline"></div>
      <p><a href="#"><i class="fa fa-angle-right"></i> Wordpress</a> <span class="badge badge-theme pull-right">9</span>
      </p>

      <p><a href="#"><i class="fa fa-angle-right"></i> Photoshop</a> <span class="badge badge-theme pull-right">3</span>
      </p>

      <p><a href="#"><i class="fa fa-angle-right"></i> Web Design</a>
        <span class="badge badge-theme pull-right">11</span></p>

      <p><a href="#"><i class="fa fa-angle-right"></i> Development</a>
        <span class="badge badge-theme pull-right">5</span></p>

      <p><a href="#"><i class="fa fa-angle-right"></i> Tips & Tricks</a>
        <span class="badge badge-theme pull-right">7</span></p>

      <p><a href="#"><i class="fa fa-angle-right"></i> Code Snippets</a>
        <span class="badge badge-theme pull-right">12</span></p>

      <div class="spacing"></div>

      <h4>Recent Posts</h4>

      <div class="hline"></div>
      <ul class="popular-posts">
        <li>
          <a href="#"><img src="img/thumb01.jpg" alt="Popular Post"></a>

          <p><a href="#">Lorem ipsum dolor sit amet consectetur adipiscing elit</a></p>
          <em>Posted on 02/21/14</em>
        </li>
        <li>
          <a href="#"><img src="img/thumb02.jpg" alt="Popular Post"></a>

          <p><a href="#">Lorem ipsum dolor sit amet consectetur adipiscing elit</a></p>
          <em>Posted on 03/01/14</em>
        <li>
          <a href="#"><img src="img/thumb03.jpg" alt="Popular Post"></a>

          <p><a href="#">Lorem ipsum dolor sit amet consectetur adipiscing elit</a></p>
          <em>Posted on 05/16/14</em>
        </li>
        <li>
          <a href="#"><img src="img/thumb04.jpg" alt="Popular Post"></a>

          <p><a href="#">Lorem ipsum dolor sit amet consectetur adipiscing elit</a></p>
          <em>Posted on 05/16/14</em>
        </li>
      </ul>

      <div class="spacing"></div>

      <h4>Popular Tags</h4>

      <div class="hline"></div>
      <p>
        <a class="btn btn-theme" href="#" role="button">Design</a>
        <a class="btn btn-theme" href="#" role="button">Wordpress</a>
        <a class="btn btn-theme" href="#" role="button">Flat</a>
        <a class="btn btn-theme" href="#" role="button">Modern</a>
        <a class="btn btn-theme" href="#" role="button">Wallpaper</a>
        <a class="btn btn-theme" href="#" role="button">HTML5</a>
        <a class="btn btn-theme" href="#" role="button">Pre-processor</a>
        <a class="btn btn-theme" href="#" role="button">Developer</a>
        <a class="btn btn-theme" href="#" role="button">Windows</a>
        <a class="btn btn-theme" href="#" role="button">Phothosop</a>
        <a class="btn btn-theme" href="#" role="button">UX</a>
        <a class="btn btn-theme" href="#" role="button">Interface</a>
        <a class="btn btn-theme" href="#" role="button">UI</a>
        <a class="btn btn-theme" href="#" role="button">Blog</a>
      </p>
    </div>
  </div>
  <!-- /row -->
</div><!-- /container -->

app/views/solid/solid/contact.html.erb
<% provide :title, 'SOLID - Bootstrap 3 Theme' %>

<!-- *****************************************************************************************************************
 BLUE WRAP
 ***************************************************************************************************************** -->
<div id="blue">
  <div class="container">
    <div class="row">
      <h3>Contact.</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /blue -->

<!-- *****************************************************************************************************************
 CONTACT WRAP
 ***************************************************************************************************************** -->

<div id="contactwrap"></div>

<!-- *****************************************************************************************************************
 CONTACT FORMS
 ***************************************************************************************************************** -->

<div class="container mtb">
  <div class="row">
    <div class="col-lg-8">
      <h4>Just Get In Touch!</h4>

      <div class="hline"></div>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s.</p>

      <form role="form">
        <div class="form-group">
          <label for="InputName1">Your Name</label>
          <input type="email" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="form-group">
          <label for="InputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="form-group">
          <label for="InputSubject1">Subject</label>
          <input type="email" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="form-group">
          <label for="message1">Message</label>
          <textarea class="form-control" id="message1" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-theme">Submit</button>
      </form>
    </div>
    <!-- /col-lg-8 -->

    <div class="col-lg-4">
      <h4>Our Address</h4>

      <div class="hline"></div>
      <p>
        Some Ave, 987,<br/>
        23890, New York,<br/>
        United States.<br/>
      </p>

      <p>
        Email: hello@solidtheme.com<br/>
        Tel: +34 8493-4893
      </p>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s.</p>
    </div>
  </div>
  <!-- /row -->
</div><!-- /container -->

app/views/solid/solid/index.html.erb
<% provide :title, 'SOLID - Bootstrap 3 Theme' %>

<!-- *****************************************************************************************************************
 HEADERWRAP
 ***************************************************************************************************************** -->
<div id="headerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h3>Show your work with this beautiful theme</h3>

        <h1>Eyecatching Bootstrap 3 Theme.</h1>
        <h5>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h5>
        <h5>More Lorem Ipsum added here too.</h5>
      </div>
      <div class="col-lg-8 col-lg-offset-2 himg">
        <img src="img/browser.png" class="img-responsive">
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /headerwrap -->

<!-- *****************************************************************************************************************
 SERVICE LOGOS
 ***************************************************************************************************************** -->
<div id="service">
  <div class="container">
    <div class="row centered">
      <div class="col-md-4">
        <i class="fa fa-heart-o"></i>
        <h4>Handsomely Crafted</h4>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
          industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book.</p>

        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
      <div class="col-md-4">
        <i class="fa fa-flask"></i>
        <h4>Retina Ready</h4>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
          industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book.</p>

        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
      <div class="col-md-4">
        <i class="fa fa-trophy"></i>
        <h4>Quality Theme</h4>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
          industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book.</p>

        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
    </div>
  </div>
  <!-- /container -->
</div><!-- /service -->

<!-- *****************************************************************************************************************
 PORTFOLIO SECTION
 ***************************************************************************************************************** -->
<div id="portfoliowrap">
  <h3>LATEST WORKS</h3>

  <%= solid_portfolio do %>
      <%= solid_portfolio_item 'A Graphic Design Item',
                               '/solid/img/portfolio/portfolio_09.jpg',
                               '/solid/img/portfolio/portfolio_09.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Web Design Item',
                               '/solid/img/portfolio/portfolio_02.jpg',
                               '/solid/img/portfolio/portfolio_02.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Graphic Design Item',
                               '/solid/img/portfolio/portfolio_03.jpg',
                               '/solid/img/portfolio/portfolio_03.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Graphic Design Item',
                               '/solid/img/portfolio/portfolio_04.jpg',
                               '/solid/img/portfolio/portfolio_04.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Book Design Item',
                               '/solid/img/portfolio/portfolio_05.jpg',
                               '/solid/img/portfolio/portfolio_05.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Graphic Design Item',
                               '/solid/img/portfolio/portfolio_06.jpg',
                               '/solid/img/portfolio/portfolio_06.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Book Design Item',
                               '/solid/img/portfolio/portfolio_07.jpg',
                               '/solid/img/portfolio/portfolio_07.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Graphic Design Item',
                               '/solid/img/portfolio/portfolio_08.jpg',
                               '/solid/img/portfolio/portfolio_08.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Web Design Item',
                               '/solid/img/portfolio/portfolio_01.jpg',
                               '/solid/img/portfolio/portfolio_01.jpg',
                               '/solid/single-project.html' %>
      <%= solid_portfolio_item 'A Book Design Item',
                               '/solid/img/portfolio/portfolio_10.jpg',
                               '/solid/img/portfolio/portfolio_10.jpg',
                               '/solid/single-project.html' %>
  <% end %>
</div><!--/Portfoliowrap -->


<!-- *****************************************************************************************************************
 MIDDLE CONTENT
 ***************************************************************************************************************** -->

<div class="container mtb">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-1">
      <h4>More About Our Agency.</h4>

      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. </p>

      <p><br/><a href="about.html.erb" class="btn btn-theme">More Info</a></p>
    </div>

    <div class="col-lg-3">
      <h4>Frequently Asked</h4>

      <div class="hline"></div>
      <p><a href="#">How cool is this theme?</a></p>

      <p><a href="#">Need a nice good-looking site?</a></p>

      <p><a href="#">Is this theme retina ready?</a></p>

      <p><a href="#">Which version of Font Awesome uses?</a></p>

      <p><a href="#">Free support is integrated?</a></p>
    </div>

    <div class="col-lg-3">
      <h4>Latest Posts</h4>

      <div class="hline"></div>
      <p><a href="single-post.html">Our new site is live now.</a></p>

      <p><a href="single-post.html">Retina ready is not an option.</a></p>

      <p><a href="single-post.html">Bootstrap 3 framework is the best.</a></p>

      <p><a href="single-post.html">You need this theme, buy it now.</a></p>

      <p><a href="single-post.html">This theme is what you need.</a></p>
    </div>

  </div>
  <!-- /row -->
</div><!-- /container -->

<%= render 'extended_footer' %>