config/routes.rb
Rails.application.routes.draw do
  #Static Pages
  root 'static_pages#home'
  get 'upgrade', to: 'static_pages#upgrade'


  resources :galleries

  resources :projects do
    resources :comments, only: [:create, :destroy] do
      collection do
        get 'new/(:parent_id)', to: 'comments#new', as: 'new'
      end
    end
    member do
      post 'like'
      delete 'unlike'
    end
  end
  get 'projects/:id/comments/:comment_id', to: 'projects#show', as: 'project_comment_show'

  get 'profile/:id', to: 'profiles#show', as: 'profile'

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             },
             skip: [:registrations, :sessions]


  get 'signin', to: 'static_pages#home', as: 'new_user_session'



  devise_scope :user do
    namespace 'users', as: 'user' do
      get 'check_username', to: 'registrations#check_username'
      get 'check_email', to: 'registrations#check_email'
      get 'check_password', to: 'registrations#check_password'
      post 'preregistration', to: 'registrations#preregistration'
    end
    namespace 'users', as: 'user_registration' do
      post '', to: 'registrations#create'
      get 'edit', to: 'registrations#edit'
      patch '', to: 'registrations#update'
      put '', to: 'registrations#update'
      delete '', to: 'registrations#destroy'
    end
    namespace 'users', as: '' do
      post 'switch_user', to: 'sessions#switch_user', as: 'user_switch_user'
      post 'sign_in', to: 'sessions#create', as: 'user_session'
      delete 'sign_out', to: 'sessions#destroy', as: 'destroy_user_session'
    end
  end

  #Announcement reading
  mount Starburst::Engine => '/starburst'

  #Routes to showcase solid layout
  namespace 'solid' do
    get 'index', to: 'solid#index'
    get 'about', to: 'solid#about'
    get 'contact', to: 'solid#contact'
    get 'blog', to: 'solid#blog'
    get 'portfolio', to: 'solid#portfolio'
    get 'single-post', to: 'solid#single_post'
    get 'single-project', to: 'solid#single_project'
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_and_belongs_to_many :projects
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  validates :title, length: { minimum: 4 }, presence: true, uniqueness: true
  validates_presence_of :author
  # validates_presence_of :thumbnail # Leave this commented out till we update views / provide default / load from projects
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  check_authorization
  load_resource
  authorize_resource only: Ability::RESTFUL_ACTIONS
  respond_to :html, :json

  def index
    respond_with(@galleries)
  end

  def show
    @projects = @gallery.projects
    respond_with(@gallery)
  end

  def new
    @projects = Project.all
    respond_with(@gallery)
  end

  def edit
  end

  def create
    @gallery.author = current_user
    @gallery.save
    respond_with(@gallery)
  end

  def update
    @gallery.update(gallery_params)
    respond_with(@gallery)
  end

  def destroy
    @gallery.destroy
    respond_with(@gallery)
  end

  private
    def gallery_params
      params.require(:gallery).permit(:title,project_ids: [])
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= semantic_form_for @gallery do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :projects, collection: @projects, label: "Projects (may select multiple): ", include_hidden: false %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<%= link_to 'New Gallery', new_gallery_path, class: 'btn btn-success btn-sm' if can? :create, Gallery %>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= link_to 'Show', gallery, class: 'btn btn-info btn-sm' %></td>
        <% if can? :edit, gallery %>
            <td><%= link_to 'Edit', edit_gallery_path(gallery), class: 'btn btn-warning btn-sm' %></td>
        <% end %>
        <% if can? :destroy, gallery %>
            <td><%= link_to 'Destroy', gallery, class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>
<p>
  <strong>Curator:</strong>
  <%= @gallery.author.username || "Uncurated" %>
</p>

<!-- *****************************************************************************************************************
 PORTFOLIO SECTION
 ***************************************************************************************************************** -->
<div id="portfoliowrap">
  <div>
    <h3>Projects:</h3>

    <%= solid_portfolio do %>
        <% @projects.each do |project| %>
            <%= solid_portfolio_item(project.title, project.thumbnail, project.thumbnail, project_path(project)) %>
        <% end %>
    <% end %>
  </div>
  <!-- portfolio container -->
</div><!--/Portfoliowrap -->

<% if can? :edit, @gallery %>
    <%= link_to 'Edit', edit_gallery_path(@gallery), class: 'btn btn-warning' %>
<% end %>
<% if can? :destroy, @gallery %>
    <%= link_to 'Destroy', @gallery, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<%= link_to 'Back', galleries_path, class: 'btn btn-default' %>