config/routes.rb
Rails.application.routes.draw do
  #Static Pages
  root 'static_pages#home'
  get 'upgrade', to: 'static_pages#upgrade'


  resources :galleries

  resources :projects do
    resources :comments, only: [:create, :destroy] do
      collection do
        get 'new/(:parent_id)', to: 'comments#new', as: 'new'
      end
    end
    member do
      post 'like'
      delete 'unlike'
    end
  end
  get 'projects/:id/comments/:comment_id', to: 'projects#show', as: 'project_comment_show'

  get 'profile/:id', to: 'profiles#show', as: 'profile'

  devise_for :users,
             controllers: {
                 omniauth_callbacks: 'users/omniauth_callbacks',
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             },
             skip: [:registrations, :sessions]


  get 'signin', to: 'static_pages#home', as: 'new_user_session'



  devise_scope :user do
    namespace 'users', as: 'user' do
      get 'check_username', to: 'registrations#check_username'
      get 'check_email', to: 'registrations#check_email'
      get 'check_password', to: 'registrations#check_password'
      post 'preregistration', to: 'registrations#preregistration'
    end
    namespace 'users', as: 'user_registration' do
      post '', to: 'registrations#create'
      get 'edit', to: 'registrations#edit'
      patch '', to: 'registrations#update'
      put '', to: 'registrations#update'
      delete '', to: 'registrations#destroy'
    end
    namespace 'users', as: '' do
      post 'switch_user', to: 'sessions#switch_user', as: 'user_switch_user'
      post 'sign_in', to: 'sessions#create', as: 'user_session'
      delete 'sign_out', to: 'sessions#destroy', as: 'destroy_user_session'
    end
  end

  #Announcement reading
  mount Starburst::Engine => '/starburst'

  #Routes to showcase solid layout
  namespace 'solid' do
    get 'index', to: 'solid#index'
    get 'about', to: 'solid#about'
    get 'contact', to: 'solid#contact'
    get 'blog', to: 'solid#blog'
    get 'portfolio', to: 'solid#portfolio'
    get 'single-post', to: 'solid#single_post'
    get 'single-project', to: 'solid#single_project'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  if Rails.env.development?
    before_action :log_current_user
  end
  helper Starburst::AnnouncementsHelper

  def log_current_user
    logger.debug "Current user: #{current_user && current_user.id}"
  end

  def sign_in_path
    '/users/sign_in'
  end

  def access_denied_handler(exception)
    if exception.is_a? CanCan::AccessDenied
      log_exception "CanCan access denied on #{exception.action} #{exception.subject.inspect}", exception
    else
      log_exception exception.message, exception
    end
    respond_to do |format|
      format.html do
        # Just give a generic error message. We don't want to tell people more than they need to know.
        flash.now[:alert] = 'You are not authorized to access that page'
        render 'unauthorized', status: :unauthorized
      end
      format.js do
        head :forbidden
      end
      format.json do
        head :forbidden
      end
    end
  end

  rescue_from CanCan::AccessDenied, with: :access_denied_handler

  rescue_from ActiveRecord::RecordNotFound, with: :access_denied_handler


  def sample_gallery_items
    [
        OpenStruct.new(
            {
                title: 'A Graphic Design Item',
                thumbnail: '/solid/img/portfolio/portfolio_09.jpg',
                url: '/solid/single-project.html'
            }),
        OpenStruct.new(
            {
                title: 'A Web Design Item',
                thumbnail: '/solid/img/portfolio/portfolio_02.jpg',
                url: '/solid/single-project.html'
            }),
        OpenStruct.new(
            {
                title: 'A Graphic Design Item',
                thumbnail: '/solid/img/portfolio/portfolio_03.jpg',
                url: '/solid/single-project.html'
            }),
        OpenStruct.new(
            {
                title: 'A Graphic Design Item',
                thumbnail: '/solid/img/portfolio/portfolio_04.jpg',
                url: '/solid/single-project.html'
            }),
        OpenStruct.new(
            {
                title: 'A Graphic Design Item',
                thumbnail: '/solid/img/portfolio/portfolio_05.jpg',
                url: '/solid/single-project.html'
            })
    ]
  end


  private
  def log_exception(message, exception)
    user_id = (current_user && current_user.id).to_s || 'nil'
    logger.info "#{message}, {requestURL #{request.path}, currentUserID #{user_id}}"
    NewRelic::Agent.notice_error(exception, uri: request.path, user_id: user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include SolidThemeHelpers
  def full_title(page_title)
    if page_title.empty?
      'LaPlaya'
    else
      page_title
    end
  end

  def alert_class_for_type(type)
    logger.debug "Processing flash of type #{type}"
    if %w(alert error).include?(type)
      'alert-danger'
    elsif %w(alert error).include?(type)
      'alert-success'
    elsif 'notice' == type
      'alert-info'
    elsif 'timedout' == type
      nil
    else
      "alert-#{type}"
    end
  end

  def controller_classes
    current_path = ''
    controller_path.split('/').map { |x| (current_path.empty?) ? current_path = x : current_path += '-' + x }.join(' ')
  end

  def nav_link(link_text, link_path, link_options = {})
    class_name = link_path && current_page?(link_path) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      if link_path
        link_to link_text, link_path, link_options
      else
        content_tag(:a, link_text, link_options)
      end
    end
  end

  def nav_button(button_text, button_options = {})
    content_tag(:li) do
      button_tag button_text, button_options
    end
  end

  def nav_dropdown(dropdown_text, &block)
    dropdown_text ||= ''
    content = capture(&block)
    class_name = content.index('active').nil? ? 'dropdown' : 'dropdown active'
    content_tag(:li, class: class_name) do
      concat (link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
               concat dropdown_text
               concat content_tag(:b, nil, class: 'caret')
             end)
      concat content_tag(:ul, content, class: 'dropdown-menu')
    end
  end

  def force_login_helper
    if @force_show_signin || @force_show_signup || @force_show_finish
      script = '$(\'#registration_modal\').modal(\'show\');'
      if @force_show_signup
        script += 'switchSigninModalToClass(\'signup\', false);'
      elsif @force_show_finish
        script += 'switchSigninModalToClass(\'finish-signup\', false);'
      end
      content_for :one_time_script, javascript_tag("$(document).ready(function(){#{script}});")
    end
  end

  def new_user
    @new_user || User.new
  end

end

app/views/application/_admin_panel.html.erb
<div class="admin-panel hidden" id="super-admin-panel">
  <script type="application/javascript">
    $(document).on('keydown', null, 'alt+a', function(){
        $('#super-admin-panel').toggleClass('hidden');
    });
  </script>
  <h5>Super Admin Panel</h5>
  <div>
    <%= render 'admin_switch_user_form' %>
  </div>
</div>

app/views/application/_admin_switch_user_form.html.erb
<u>Login as another user</u>
<%= form_tag user_switch_user_path, method: :post, class: 'form' do %>
    <div class="form-group">
      <%= label_tag 'user_id', 'User', class: 'sr-only' %>
      <%= select_tag 'user_id', options_from_collection_for_select(User.all, :id, :username), class: 'form-control' %>
    </div>
    <div class="checkbox">
      <%= label_tag 'remember' do %>
          <% concat check_box_tag 'remember', 'true' %>
          <% concat 'Log me back in when I am done' %>
      <% end %>
    </div>
    <button type="submit" class="btn btn-default">Switch to User</button>
<% end %>

app/views/application/_announcement.html.erb
<% if current_announcement %>
    <div id="announcements">
      <div class="starburst-announcement container">
        <%= link_to "Close", starburst.mark_as_read_path(current_announcement.id), :method => :post, :remote => true, :id => "starburst-close", class: 'pull-right' %>
        <p><%= current_announcement.body.html_safe %></p>
      </div>
    </div>
<% end %>

app/views/application/_footer.html.erb
<!-- *****************************************************************************************************************
 FOOTER
 ***************************************************************************************************************** -->
<div id="footerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h4>About</h4>

        <div class="hline-w"></div>
        <p>LaPlaya is a site for students to share Blockly programming projects. <a href="https://developers.google.com/blockly/">Blockly</a>
            is a library for building visual programming editors</p>
      </div>
      <div class="col-lg-4">
        <h4>Social Links</h4>

        <div class="hline-w"></div>
        <p>
          <a href="https://github.com/scalableinternetservices/LaPlaya"><i class="fa fa-github"></i></a>
          <a href="#"><i class="fa fa-dribbble"></i></a>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-tumblr"></i></a>
        </p>
      </div>
      <div class="col-lg-4">
        <h4>Our Bunker</h4>

        <div class="hline-w"></div>
        <p>
          2510 Phelps Hall<br/>
          University Of California, Santa Barbara<br/>
          Santa Barbara, CA 93106<br/>
          United States.<br/>
        </p>
      </div>

    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /footerwrap -->

app/views/application/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <%= render partial: 'announcement' %>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'LaPlaya', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <%= nav_link 'HOME', root_path %>
        <%= nav_link 'PROJECTS', projects_path %>
        <%= nav_link 'GALLERIES', galleries_path %>
        <% if user_signed_in? %>
            <%= nav_dropdown current_user.username do %>
                <%= nav_link 'My Profile', profile_path(current_user) %>
                <%= nav_link 'Sign Out', destroy_user_session_path, method: :delete %>
            <% end %>
        <% else %>
            <%= nav_link 'Sign In / Sign Up', nil, {id: 'signin_link', class: 'empty-link', 'data-toggle' => 'modal', 'data-target' => '#registration_modal'} %>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
  <%= render 'layouts/flashes' %>
</div>

app/views/application/_login_button.html.erb
<%= link_to path, link_options do %>
    <i class="<%= icon_class %>"></i>
    <span class="signin">Sign in</span>
    <span class="signup hidden">Sign up</span>
    <%= link_text %>
<% end %>

app/views/application/_login_modal.html.erb
<div class="modal fade" id="registration_modal" role="dialog" aria-labelledby="registration" aria-describedby="Registration and Login Dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title signin">Sign in...</h4>
        <h4 class="modal-title signup hidden">Sign up...</h4>
        <h4 class="modal-title finish-signup hidden">Choose a username...</h4>
      </div>
      <div class="modal-body">
        <div class="signin signup">
          <div>

            <%= render partial: 'login_button',
                       locals: {
                               path: user_omniauth_authorize_path(:facebook),
                               link_options: {
                                       class: 'btn btn-block btn-social btn-facebook',
                                       'data-popup' => true
                               },
                               icon_class: 'fa fa-facebook',
                               link_text: 'with Facebook'} %>
          </div>
          <hr>
          <div class="signin">
            <%= render partial: 'signin_form' %>
          </div>
          <div class="signup hidden">
            <%= render partial: 'signup_email_form' %>
          </div>
          <hr>
          <div id="sign_up_switcher">
            <a class="empty-link signin">Don't have an account? Create one today!</a>
            <a class="empty-link signup hidden">Already have an account?</a>
          </div>
        </div>
        <div class="finish-signup hidden">
          <%= render partial: 'signup_finish' %>
        </div>
      </div>
      <div class="modal-footer">
        <input type="submit" form="signin-form" class="btn btn-primary signin" value="Sign in"/>
        <input id="email-signup-button" type="submit" form="signup-email-form" class="btn btn-primary signup hidden" value="Next..."/>
        <button id="cancel-signup" class="btn btn-default finish-signup hidden">Back</button>
        <input id="finish-signup-button" type="submit" form="finish-signup-form" class="btn btn-primary finish-signup hidden" value="Sign up!"/>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/application/_signin_form.html.erb
<%= form_tag user_session_path, id: 'signin-form', class: 'compact-form' do %>
    <h5 class="heading">Or sign in using your email</h5>
    <div class="form-group top">
      <%= text_field_tag 'user[email]', nil,
                         placeholder: 'email',
                         class: 'form-control email',
                         type: 'email'
      %>
    </div>
    <div class="form-group bottom">
      <%= text_field_tag 'user[password]', nil,
                         placeholder: 'password',
                         class: 'form-control password',
                         type: 'password'
      %>
    </div>
<% end %>

app/views/application/_signup_email_form.html.erb
<%= semantic_form_for new_user, url: user_preregistration_path, html: {
                                      id: 'signup-email-form',
                                      class: 'compact-form',
                                      remote: true
                              } do |f| %>
    <h5 class="heading">Or sign up using your email</h5>
    <%= f.semantic_errors :email, :password, :password_confirmation, :provider, :uid, :username %>
    <%= f.input :email, placeholder: 'email', label: false, wrapper_html: {class: 'top'} %>
    <%= f.input :password, placeholder: 'password', label: false, wrapper_html: {class: 'middle'} %>
    <%= f.input :password_confirmation, placeholder: 'password_confirmation', label: false, wrapper_html: {class: 'bottom'} %>
<% end %>

app/views/application/_signup_finish.html.erb
<h5>
  You are almost done...
</h5>
<p>
  Pick your new username...
</p>
<%= semantic_form_for new_user, url: user_registration_path, html: {
                                                   id: 'finish-signup-form',
                                                   class: 'compact-form'
                                           } do |f| %>
    <%= f.semantic_errors :email, :password, :password_confirmation, :provider, :uid, :username %>
    <%= f.input :username, placeholder: 'username', label: false %>
<% end %>

app/views/application/unauthorized.html.erb
<div id="headerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h3>There was an error with your request..</h3>
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div><!-- /headerwrap -->